# Copyright 2025 Ecosoft Co., Ltd. (http://ecosoft.co.th)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo.tests.common import TransactionCase


class TestQualityControlType(TransactionCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.inspection_model = cls.env["qc.inspection"]
        cls.qc_type = cls.env["qc.inspection.type"]
        # Standard Sequence
        cls.prefix_standard_sequence = cls.env.ref(
            "quality_control_oca.seq_qc_inspection"
        ).prefix
        # Type not sequence
        cls.type_no_sequence = cls.env.ref("quality_control_type_oca.qc_type_generic")
        # Type sequence
        cls.qc_type_sequence = cls.env["ir.sequence"].create(
            {
                "name": "Test Sequence",
                "code": "test.sequence",
                "prefix": "QC_TYPE_TEST/",
                "padding": 3,
            }
        )
        cls.type_with_sequence = cls.env.ref(
            "quality_control_type_oca.qc_type_generic"
        ).copy()
        cls.type_with_sequence.sequence_id = cls.qc_type_sequence.id

    def test_01_inspection_no_type(self):
        inspection = self.inspection_model.create({"name": "/", "type_id": False})
        self.assertTrue(inspection.name.startswith(self.prefix_standard_sequence))

    def test_02_inspection_type_without_sequence(self):
        inspection = self.inspection_model.create(
            {"name": "/", "type_id": self.type_no_sequence.id}
        )
        self.assertTrue(inspection.name.startswith(self.prefix_standard_sequence))

    def test_03_inspection_type_with_sequence(self):
        inspection = self.inspection_model.create(
            {"name": "/", "type_id": self.type_with_sequence.id}
        )
        # Check name is generated by sequence, it should be start with QC_TYPE_TEST/
        self.assertTrue(inspection.name.startswith("QC_TYPE_TEST/"))
