SUBCONTRACTOR_TYPE_SELECTION_BUY_MTS_MTO = "mts_mto"

SUBCONTRACTOR_TYPE_SELECTION_BUY = "buy"

SUBCONTRACTOR_TYPE_SELECTION = [
    (SUBCONTRACTOR_TYPE_SELECTION_BUY, "Buy"),
    (SUBCONTRACTOR_TYPE_SELECTION_BUY_MTS_MTO, "MTS+MTO"),
]
