# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.3.6
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: Odoo modules related to Manufacturing
repo_name: Odoo Manufacturing Modules
repo_slug: manufacture
travis_apt_packages: []
travis_apt_sources: []
