{
    "name": "MRP Workorder Subcontracting",
    "summary": "Manage subcontracting flows linked to manufacturing work orders",
    "version": "18.0.1.0.0",
    "category": "Manufacturing",
    "website": "https://github.com/OCA/manufacture",
    "license": "AGPL-3",
    "author": "Dealtech Srl, Openindustry.it, Odoo Community Association (OCA)",
    "depends": [
        "mrp",
        "purchase_stock",
        "purchase_order_type",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/res_groups.xml",
        "data/ir_sequence_data.xml",
        "data/stock_location_data.xml",
        "data/stock_picking_type_data.xml",
        "data/purchase_order_type_data.xml",
        "views/mrp_production_views.xml",
        "views/mrp_routing_workcenter_views.xml",
        "views/mrp_workorder_views.xml",
        "views/purchase_order_views.xml",
        "views/purchase_order_line_views.xml",
        "views/purchase_order_type_views.xml",
        "views/res_partner_views.xml",
        "views/stock_move_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_picking_type_views.xml",
        "views/stock_warehouse_views.xml",
        "wizards/mrp_workorder_assign_subcontract.xml",
        "wizards/purchase_order_subcontract_bid_confirm.xml",
    ],
    "installable": True,
    "application": False,
    "development_status": "Alpha",
    "maintainers": ["aleboldro02"],
}
