{
    "name": "MRP Workorder Subcontracting",
    "summary": "Manage subcontracting flows linked to manufacturing work orders",
    "version": "18.0.1.0.0",
    "website": "https://github.com/OCA/manufacture",
    "license": "AGPL-3",
    "author": "Dealtech Srl, Openindustry.it, Odoo Community Association (OCA)",
    "depends": [
        "mrp",
        "purchase_stock",
        "purchase_order_type",
    ],
    "data": [
        "views/mrp_routing_workcenter.xml",
        "views/purchase_order_line.xml",
        "views/purchase_order_type.xml",
        "views/res_partner.xml",
        "views/stock_picking_type.xml",
        "views/stock_warehouse.xml",
    ],
    "installable": True,
    "application": False,
    "development_status": "Alpha",
    "maintainers": ["aleboldro02"],
}
