# Copyright 2017-19 ForgeFlow S.L.
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).


from collections import defaultdict

from odoo import _, api, fields, models
from odoo.exceptions import UserError


class MrpProductionRequest(models.Model):
    _name = "mrp.production.request"
    _description = "Manufacturing Request"
    _inherit = "mail.thread"
    _order = "date_start desc, id desc"

    @api.model
    def _get_default_requested_by(self):
        return self.env.user

    name = fields.Char(
        default="/",
        required=True,
        readonly=False,
    )
    origin = fields.Char(
        string="Source Document",
        readonly=False,
    )
    requested_by = fields.Many2one(
        comodel_name="res.users",
        string="Requested by",
        default=lambda self: self._get_default_requested_by(),
        required=True,
        tracking=True,
        readonly=False,
    )
    assigned_to = fields.Many2one(
        comodel_name="res.users",
        string="Approver",
        tracking=True,
        readonly=False,
        domain=lambda self: [
            (
                "groups_id",
                "in",
                self.env.ref(
                    "mrp_production_request.group_mrp_production_request_manager"
                ).id,
            )
        ],
    )
    description = fields.Text()
    date_start = fields.Datetime(
        string="Start",
        copy=False,
        default=fields.Datetime.now,
        index=True,
        required=True,
    )
    date_finished = fields.Datetime(
        string="End",
        copy=False,
        default=fields.Datetime.now,
        index=True,
    )
    company_id = fields.Many2one(
        comodel_name="res.company",
        string="Company",
        required=True,
        default=lambda self: self.env.company,
    )
    mrp_production_ids = fields.One2many(
        comodel_name="mrp.production",
        string="Manufacturing Orders",
        inverse_name="mrp_production_request_id",
        readonly=True,
    )
    mrp_production_count = fields.Integer(
        compute="_compute_mrp_production_count", string="MO's Count"
    )
    state = fields.Selection(
        selection=[
            ("draft", "Draft"),
            ("to_approve", "To Be Approved"),
            ("approved", "Approved"),
            ("done", "Done"),
            ("cancel", "Cancelled"),
        ],
        index=True,
        tracking=True,
        required=True,
        copy=False,
        default="draft",
    )
    procurement_group_id = fields.Many2one(
        string="Procurement Group", comodel_name="procurement.group", copy=False
    )
    propagate = fields.Boolean(
        string="Propagate cancel and split",
        help="If checked, when the previous move of the move "
        "(which was generated by a next procurement) is cancelled "
        "or split, the move generated by this move will too",
    )
    product_id = fields.Many2one(
        comodel_name="product.product",
        string="Product",
        required=True,
        domain=[("type", "=", "consu")],
        compute="_compute_product_id",
        store=True,
        copy=True,
        precompute=True,
        check_company=True,
        tracking=True,
        readonly=False,
    )
    product_tmpl_id = fields.Many2one(
        comodel_name="product.template",
        string="Product Template",
        related="product_id.product_tmpl_id",
    )
    product_qty = fields.Float(
        string="Required Quantity",
        required=True,
        tracking=True,
        digits="Product Unit of Measure",
        default=1.0,
        readonly=False,
    )
    product_uom_id = fields.Many2one(
        comodel_name="uom.uom",
        string="Unit of Measure",
        readonly=False,
        required=True,
        compute="_compute_uom_id",
        store=True,
        copy=True,
        precompute=True,
        domain="[('category_id', '=', category_uom_id)]",
    )
    category_uom_id = fields.Many2one(
        related="product_uom_id.category_id",
    )
    manufactured_qty = fields.Float(
        string="Quantity in Manufacturing Orders",
        compute="_compute_manufactured_qty",
        store=True,
        readonly=True,
        digits="Product Unit of Measure",
        help="Sum of the quantities in Manufacturing Orders (in any state).",
    )
    done_qty = fields.Float(
        string="Quantity Done",
        store=True,
        readonly=True,
        compute="_compute_manufactured_qty",
        digits="Product Unit of Measure",
        help="Sum of the quantities in all done Manufacturing Orders.",
    )
    pending_qty = fields.Float(
        string="Pending Quantity",
        compute="_compute_manufactured_qty",
        store=True,
        digits="Product Unit of Measure",
        readonly=True,
        help="Quantity pending to add to Manufacturing Orders "
        "to fulfill the Manufacturing Request requirement.",
    )
    bom_id = fields.Many2one(
        comodel_name="mrp.bom",
        string="Bill of Materials",
        required=True,
        readonly=False,
        domain="""[
        '&',
            '|',
                ('company_id', '=', False),
                ('company_id', '=', company_id),
            '&',
                '|',
                    ('product_id','=',product_id),
                    '&',
                        ('product_tmpl_id.product_variant_ids','=',product_id),
                        ('product_id','=',False),
        ('type', '=', 'normal')]""",
        check_company=True,
        compute="_compute_bom_id",
        store=True,
        precompute=True,
        help="Bills of Materials, also called recipes, are used to autocomplete "
        "components and work order instructions.",
    )
    location_src_id = fields.Many2one(
        comodel_name="stock.location",
        string="Components Location",
        compute="_compute_locations",
        store=True,
        check_company=True,
        readonly=False,
        required=True,
        precompute=True,
        domain="[('usage','=','internal')]",
        help="Location where the system will look for components.",
    )
    location_dest_id = fields.Many2one(
        comodel_name="stock.location",
        string="Finished Products Location",
        compute="_compute_locations",
        store=True,
        check_company=True,
        readonly=False,
        required=True,
        precompute=True,
        domain="[('usage','=','internal')]",
        help="Location where the system will stock the finished products.",
    )
    picking_type_id = fields.Many2one(
        comodel_name="stock.picking.type",
        string="Operation Type",
        compute="_compute_picking_type_id",
        store=True,
        check_company=True,
        readonly=False,
        required=True,
        precompute=True,
        domain="[('code', '=', 'mrp_operation')]",
        index=True,
    )
    move_dest_ids = fields.One2many(
        comodel_name="stock.move",
        inverse_name="created_mrp_production_request_id",
        string="Stock Movements of Produced Goods",
    )
    orderpoint_id = fields.Many2one(
        comodel_name="stock.warehouse.orderpoint",
        string="Orderpoint",
    )

    _sql_constraints = [
        (
            "name_uniq",
            "unique(name, company_id)",
            "Reference must be unique per Company!",
        )
    ]

    @api.model
    def _get_mo_valid_states(self):
        return ["draft", "confirmed", "progress", "to_close", "done"]

    @api.model
    def _get_mo_done_states(self):
        return ["done"]

    @api.depends("mrp_production_ids", "mrp_production_ids.state", "state")
    def _compute_manufactured_qty(self):
        valid_states = self._get_mo_valid_states()
        done_states = self._get_mo_done_states()
        for req in self:
            done_mo = req.mrp_production_ids.filtered(
                lambda mo: mo.state in done_states
            ).mapped("product_qty")
            req.done_qty = sum(done_mo)
            valid_mo = req.mrp_production_ids.filtered(
                lambda mo: mo.state in valid_states
            ).mapped("product_qty")
            req.manufactured_qty = sum(valid_mo)
            req.pending_qty = max(req.product_qty - req.manufactured_qty, 0.0)

    def _compute_mrp_production_count(self):
        for rec in self:
            rec.mrp_production_count = len(rec.mrp_production_ids)

    @api.depends("company_id", "bom_id")
    def _compute_picking_type_id(self):
        """Implementation is a direct copy of
        `mrp.production._compute_picking_type_id()`"""
        domain = [
            ("code", "=", "mrp_operation"),
            ("warehouse_id.company_id", "in", self.company_id.ids),
        ]
        picking_types = self.env["stock.picking.type"].search_read(
            domain, ["company_id"], load=False, limit=1
        )
        picking_type_by_company = {pt["company_id"]: pt["id"] for pt in picking_types}
        default_picking_type_id = self._context.get("default_picking_type_id")
        default_picking_type = default_picking_type_id and self.env[
            "stock.picking.type"
        ].browse(default_picking_type_id)
        for rec in self:
            if (
                default_picking_type
                and default_picking_type.company_id == rec.company_id
            ):
                rec.picking_type_id = default_picking_type_id
                continue
            if rec.bom_id and rec.bom_id.picking_type_id:
                rec.picking_type_id = rec.bom_id.picking_type_id
                continue
            if rec.picking_type_id and rec.picking_type_id.company_id == rec.company_id:
                continue
            rec.picking_type_id = picking_type_by_company.get(rec.company_id.id, False)
            company_warehouse = self.env["stock.warehouse"].search(
                [("company_id", "=", rec.company_id.id)], limit=1
            )
            if not company_warehouse:
                self.env["stock.warehouse"]._warehouse_redirect_warning()

    @api.depends("picking_type_id")
    def _compute_locations(self):
        """Implementation is a direct copy of `mrp.production._compute_locations()`"""
        for rec in self:
            if (
                not rec.picking_type_id.default_location_src_id
                or not rec.picking_type_id.default_location_dest_id
            ):
                company_id = (
                    rec.company_id.id
                    if (rec.company_id and rec.company_id in self.env.companies)
                    else self.env.company.id
                )
                fallback_loc = (
                    self.env["stock.warehouse"]
                    .search([("company_id", "=", company_id)], limit=1)
                    .lot_stock_id
                )
            rec.location_src_id = (
                rec.picking_type_id.default_location_src_id.id or fallback_loc.id
            )
            rec.location_dest_id = (
                rec.picking_type_id.default_location_dest_id.id or fallback_loc.id
            )

    @api.depends("bom_id", "product_id")
    def _compute_uom_id(self):
        """Implementation is a direct copy of `mrp.production._compute_uom_id()`"""
        for rec in self:
            if rec.state != "draft":
                continue
            if rec.bom_id and rec._origin.bom_id != rec.bom_id:
                rec.product_uom_id = rec.bom_id.product_uom_id
            elif rec.product_id:
                rec.product_uom_id = rec.product_id.uom_id
            else:
                rec.product_uom_id = False

    @api.depends("bom_id")
    def _compute_product_id(self):
        """Implementation is a direct copy of `mrp.production._compute_product_id()`"""
        for rec in self:
            bom = rec.bom_id
            if bom and (
                not rec.product_id
                or bom.product_tmpl_id != rec.product_id.product_tmpl_id
                or bom.product_id
                and bom.product_id != rec.product_id
            ):
                rec.product_id = (
                    bom.product_id or bom.product_tmpl_id.product_variant_id
                )

    @api.depends("product_id")
    def _compute_bom_id(self):
        """Implementation is a direct copy of `mrp.production._compute_bom_id()`"""
        mr_by_company_id = defaultdict(lambda: self.env["mrp.production.request"])
        for rec in self:
            if not rec.product_id and not rec.bom_id:
                rec.bom_id = False
                continue
            mr_by_company_id[rec.company_id.id] |= rec

        picking_type_id = self._context.get("default_picking_type_id")
        picking_type = picking_type_id and self.env["stock.picking.type"].browse(
            picking_type_id
        )
        for company_id, requests in mr_by_company_id.items():
            boms_by_product = (
                self.env["mrp.bom"]
                .with_context(active_test=True)
                ._bom_find(
                    requests.product_id,
                    picking_type=picking_type,
                    company_id=company_id,
                    bom_type="normal",
                )
            )
            for request in requests:
                if (
                    not request.bom_id
                    or request.bom_id.product_tmpl_id != request.product_tmpl_id
                    or (
                        request.bom_id.product_id
                        and request.bom_id.product_id != request.product_id
                    )
                ):
                    bom = boms_by_product[request.product_id]
                    request.bom_id = bom.id or False
                    self.env.add_to_compute(request._fields["picking_type_id"], request)

    def _subscribe_assigned_user(self, vals):
        self.ensure_one()
        if vals.get("assigned_to"):
            self.message_subscribe(
                partner_ids=self.assigned_to.mapped("partner_id").ids
            )

    @api.model
    def _create_sequence(self, vals):
        if not vals.get("name") or vals.get("name") == "/":
            vals["name"] = (
                self.env["ir.sequence"].next_by_code("mrp.production.request") or "/"
            )
        return vals

    @api.model
    def create(self, vals):
        """Add sequence if name is not defined and subscribe to the thread
        the user assigned to the request."""
        vals = self._create_sequence(vals)
        res = super().create(vals)
        res._subscribe_assigned_user(vals)
        return res

    def write(self, vals):
        res = super().write(vals)
        for request in self:
            request._subscribe_assigned_user(vals)
        return res

    @api.returns("self", lambda value: value.id)
    def copy(self, default=None):
        if default is None:
            default = {}
        default = self._create_sequence(default)
        production_request_id = super().copy(default)
        return production_request_id

    def button_to_approve(self):
        self.write({"state": "to_approve"})
        return True

    def button_approved(self):
        self.write(
            {
                "state": "approved",
                "assigned_to": self.env.uid,
            }
        )
        return True

    def button_done(self):
        self.write({"state": "done"})
        return True

    def _check_reset_allowed(self):
        if any(
            [
                s in self._get_mo_valid_states()
                for s in self.mapped("mrp_production_ids.state")
            ]
        ):
            raise UserError(
                _(
                    "You cannot reset a manufacturing request if the related "
                    "manufacturing orders are not cancelled."
                )
            )

    def button_draft(self):
        self._check_reset_allowed()
        self.write({"state": "draft"})
        return True

    def _check_cancel_allowed(self):
        if any([s == "done" for s in self.mapped("state")]):
            raise UserError(
                _(
                    "You cannot reject a manufacturing request related to "
                    "done procurement orders."
                )
            )

    def button_cancel(self):
        self._check_cancel_allowed()
        self.write({"state": "cancel"})
        self.mapped("move_dest_ids").filtered(
            lambda r: r.state != "cancel"
        )._action_cancel()
        return True

    def action_view_mrp_productions(self):
        action = self.env["ir.actions.act_window"]._for_xml_id(
            "mrp.mrp_production_action"
        )
        action["context"] = {}
        mos = self.mapped("mrp_production_ids")
        # choose the view_mode accordingly
        if len(mos) != 1:
            action["domain"] = [("id", "in", mos.ids)]
        elif len(mos) == 1:
            form = self.env.ref("mrp.mrp_production_form_view", False)
            action["views"] = [(form and form.id or False, "form")]
            action["res_id"] = mos[0].id
        return action
