[project]
name = "odoo-addons-oca-manufacture"
version = "19.0.20260720.0"
dependencies = [
    "odoo-addon-mrp_attachment_mgmt==19.0.*",
    "odoo-addon-mrp_bom_component_menu==19.0.*",
    "odoo-addon-mrp_bom_image==19.0.*",
    "odoo-addon-mrp_bom_note==19.0.*",
    "odoo-addon-mrp_bom_tracking==19.0.*",
    "odoo-addon-mrp_multi_level==19.0.*",
    "odoo-addon-mrp_production_back_to_draft==19.0.*",
    "odoo-addon-mrp_production_note==19.0.*",
    "odoo-addon-mrp_repair_order==19.0.*",
    "odoo-addon-mrp_sale_info==19.0.*",
    "odoo-addon-mrp_subcontracting_purchase_link==19.0.*",
    "odoo-addon-mrp_subcontracting_skip_no_negative==19.0.*",
    "odoo-addon-mrp_tag==19.0.*",
    "odoo-addon-mrp_warehouse_calendar==19.0.*",
    "odoo-addon-quality_control_oca==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
